config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'user/new'
  get 'static_pages/home'
  get 'static_pages/help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  delete '/logout', to:"sessions#destroy"
  get '/login' , to: "sessions#new"
  post '/login' , to: "sessions#create"
  get "/signup", to: "user#new"
  post "/signup",to:"user#create"
  get '/help', to: 'static_pages#help' 
  get '/about', to: 'static_pages#about'

  post '/create', to:"user#create"
  # get "/user/show", to: "user#show"
  get 'users/:id', to: 'user#show'

  # get "users/signup", to: "users#new"
  post "user/new",to: "user#create"

  get "/all", to: "user#all"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token

	validates :name, presence: true,length: {maximum: 50}

	before_save { email.downcase! }
  	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true,length: {maximum: 255},format: {with:VALID_EMAIL_REGEX}, uniqueness: true
	
	has_secure_password
  	validates :password,presence: true, length: { minimum: 6 }

  	def User.digest string
 		cost = if ActiveModel::SecurePassword.min_cost
    		BCrypt::Engine::MIN_COST
 				else
  			BCrypt::Engine.cost
				end
			BCrypt::Password.create string, cost: cost
	end

	class << self
		def new_token
			SecureRandom.urlsafe_base64
		end
	end

	def remember
		self.remember_token = User.new_token
		update_attribute :remember_digest, User.digest(remember_token)
	end

	def authenticated? 
		remember_token BCrypt::Password.new(remember_digest).is_password? remember_token
	end

	def forget
  		update_attribute :remember_digest, nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user= User.find_by email:params[:session][:email].downcase
	 if user.try(:authenticate, params[:session][:password])
    		log_in user
       
     		redirect_to user
 	  else
	# Log the user in and redirect to the user's show page.
	 # Create an error message.
	 flash.now[:danger] = t "invalid_email_password_combination"
 	render :new
	end
  end

  def destroy
    log_out
 	  redirect_to root_url
  end

  def current_user
    if (user_id = session[:user_id])
        @current_user ||= User.find_by id: user_id 
      elsif (user_id = cookies.signed[:user_id])
          user = User.find_by id: user_id
          if user&.authenticated?(cookies[:remember_token])
              log_in user
              @current_user = user 
          end
      end 
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def new
  	@user = User.new
  end

  def show
  	begin
  		@user = User.find_by id:params[:id]
  	rescue Exception => e
 		
  	end
  end

#   def create
#    @user = User.new params[:user]
# 	if @user.save
# # Not the final implementation!
#     else
# # Handle a successful save.
# 		render :new
#    end
	def all
		@user = User.all
	end

	def create
		@user = User.new(user_params)
		#debugger
		if @user.save
			log_in @user
			flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		 else
		 	@user
		 	render :error_messages
		end

	end

	private 
	def user_params
		params.require(:user).permit :name,:email,:password,:password_confirmation
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
		session[:user_id] = user.id
		
	end

	def current_user 
		@current_user ||= User.find_by id:session[:user_id]
		
	end

	def logged_in?
		current_user.present?
	end

	def log_out
		forget(current_user) 
		session.delete(:user_id)
		@current_user= nil
	end

	def remember user
		user.remember
		cookies.permanent.signed[:user_id] = user.id 
		cookies.permanent[:remember_token] = user.remember_token
	end


	def forget(user)
		user.forget 
		cookies.delete(:user_id) 
		cookies.delete(:remember_token)
	end
# Logs out the current user.
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def full_title page_title= ""
		base_title = "Ruby on Rails Tutorial Sample App "
		page_title.empty? ? base_title : "#{page_title} | #{base_title}" 
	end
end

app/helpers/user_helper.rb
module UserHelper

	def gravatar_for user
 
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
 		gravatar_url= "https://secure.gravatar.com/avatar/#{gravatar_id}"
 		image_tag(gravatar_url, alt: user.name, class:"gravatar")
	end
end

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse"> 
 	<div class="container">
	<%= link_to "sample app", root_path, id: "logo" %> 
	<nav>
		<ul class="nav navbar-nav navbar-right"> 
			<li><%= link_to "Home", root_path %></li> 
			<li><%= link_to "Help", help_path %></li>
			<% if logged_in? %>
				<li><%= link_to "Users", '#' %></li> <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Profile", current_user %></li> 
					<li><%= link_to "Settings", '#' %></li>
					<li class="divider"></li>
					<li><%= link_to "Log out", logout_path, method: :delete,data: { confirm: 'Are you sure?' } %> </li>
				</ul> 
			</li>
			<% else %>
				<li><%= link_to "Log in", login_path %></li>
			<% end %> 
			</ul>
		</nav>
	 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %> 
   
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %> 
	<div id="error_explanation">
		<div class="alert alert-danger"> 
			<%= t "the_form_contains" %>
			<%= pluralize @user.errors.count, "error" %>. 
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
	      	<li><%= msg %></li>
		<% end %>
	    </ul>
  	</div>
<% end %>

app/views/static_pages/help.html.erb
<% provide :title , "Home" %> 

<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://www.railstutorial.org/help">Rails Tutorial
help page</a>.
  To get help on this sample app, see the
<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
book</a>. </p>

app/views/static_pages/home.html.erb
<% provide :title , "Home" %> 

<h1>Sample App</h1>
<p>
This is the home page for the
<a href="http://www.railstutorial.org/">Ruby on
Rails Tutorial</a> sample application.
</p>

app/views/user/all.html.erb
<% provide(@user) %> 
<% provide :title , "View Detail User" %> 
<div class="row">
<aside class="col-md-4"> 
	<section class="user_info">
		<% @user.each |item| do %> 
		<h1><%= item.name %> 
			<%= gravatar_for item %></h1>
		<h1><%= item.email %></h1>
		<h1><%= item.created_at %></h1>
		<% end %> 
	</section>
</aside> 
</div>

app/views/user/new.html.erb
<% provide  t("sign_up") %> 
<% provide :title , "Create User"%> 
<h1 style="text-align: center;">Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user ,url: "/user/new", method: "post") do |f| %> 
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :email %>
			<%= f.email_field :email %>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.label :password_confirmation, t("confirmation") %>
			<%= f.password_field :password_confirmation %>
			<%= f.submit "Create my account", class: "btn btn-primary" %>
	    <% end %>
	 </div>
</div>

app/views/user/show.html.erb
<% provide(@user) %> 
<% provide :title , "View Detail User" %> 
<div class="row">
<aside class="col-md-4"> 
	<section class="user_info">
		<h1><%= @user.name %> <%= gravatar_for @user %></h1>
		<h1><%= @user.email %></h1>
		<h1><%= @user.created_at %></h1>
	</section>
</aside> 
</div>